import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { LampDemo } from "./components/ui/lamp";

const chakra = Chakra_Petch({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chakra.className} `} style={{ overflowX: "hidden" }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
